version: "3.7"
services:
  image-gallery:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      UNSPLASH_API: ${UNSPLASH_API}
    container_name: image-gallery
    ports:
      - "3000:3000"
    restart: always